[versions]
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "35"
agp = "8.13.1"
gson = "2.10.1"
kotlin = "2.2.21"

androidx-core = "1.17.0"
androidx-lifecycle = "2.9.6"
androidx-activityCompose = "1.12.0"
androidx-compose = "1.2.1"

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
nativeCocoaPods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }